version: '3.8'

services:
  blog:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=postgres
      - DB_USER=admin
      - DB_PASSWORD=578nwmOLN
      - DB_NAME=blog
    depends_on:
      postgres:
        condition: service_healthy
    command: ["go", "mod", "download"]

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 578nwmOLN
      POSTGRES_DB: blog
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d blog -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
