version: '3.8'

services:
  blog:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=postgres
      - DB_USER=admin
      - DB_PASSWORD=578nwmOLN
      - DB_NAME=blog
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 578nwmOLN
      POSTGRES_DB: blog
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: